### ISSUE TITLE
DiscussionController@store - unable to create discussion

### ISSUE THREAD

**Issue by AndreasElia** [bitporch/laravel-forum#102]
Something about the `group_id` not having a default value, but it is passed through from the request.

**Comment by Dylan-DPC** [comment]
can you post the error along with the steps to reproduce?

**Comment by AndreasElia** [comment]
The error is literally about the group_id not having a default value, setup the project and try creating a discussion and you'll see the issue.

**Comment by tomirons** [comment]
Working on this... 😄

**Comment by AndreasElia** [comment]
This is pretty much identical to #103 - discussions can't be created. The discussions will need a few changes to work with the group/discussion pivot table in PR #111 anyway.
