### ISSUE TITLE
Uniform lists for posts/discussions/groups etc.

### ISSUE THREAD

**Issue by AndreasElia** [bitporch/laravel-forum#105]
Best to have at least some uniformity 😄

**Comment by Dylan-DPC** [comment]
more details?

**Comment by AndreasElia** [comment]
Well for one I'm using the Bootstrap list groups instead of the panel body for most of the project, but am using list groups within the panel body elsewhere on the project. This just needs cleaning up so it is uniform 😄

**Comment by AndreasElia** [comment]
Decided I'll fix this in #100
