### ISSUE TITLE
Circular dependency problem with first post 

### ISSUE THREAD

**Issue by Dylan-DPC** [bitporch/laravel-forum#138]
Ok, so now, as you can see, there are some issues with the factory data during tests. This is mainly because at some point I need to create a Post. This post belongs to a Discussion, but since the discussion requires a valid first_post_id I also need to create a Post. Well, you kind of see the circular dependency right?

So my best guess was to split up the factory definitions into attribute only and relational data. This can be achieved by just defining the attribute values when using $factory->define. For each relation we can create a state.

Maybe it's best explained by an example:
```php
// instead of
$factory->define('post', function ($faker) {
    return [
        'discussion_id' => factory('discussion'),
        'user_id'       => factory('user'),
        'content'       => $faker->text,
    ];
});

// we can define the attributes
$factory->define('post', function ($faker) {
    return ['content' => $faker->text];
});

// and for each relation something like this
$factory->state('post', 'discussion', function ($faker) {
    return ['discussion_id' => factory('discussion')];
});
```
This will remove the circular dependency, but requires a little more overhead when using them.
Source: Cedric's PR

**Comment by Dylan-DPC** [comment]
taken from #137

**Comment by byCedric** [comment]
Of course this is will be one from many fixes, but what do you guys think? Is it _good enough_ or has someone a better option?

**Comment by Dylan-DPC** [comment]
we could have an observer that automatically updates the `first_post_id` after the first post is created?

**Comment by byCedric** [comment]
Yes, that's possible for this scenario. But keep in mind that something like that doesn't "fix" a next possible circular dependency issue with the factory.

**Comment by Dylan-DPC** [comment]
Just thinking of it again I don't think its a good idea to store `first_post_id` on the discussion. Instead we could pick the first one based on a timestamp or something

**Comment by AndreasElia** [comment]
I think the column is fine and is something the post observer should handle. If we wanted to have stickied posts in the future and have them display at the top the column would come into even bigger use.

**Comment by Dylan-DPC** [comment]
Why do we a need a `first_post_id` on discussion?

**Comment by AndreasElia** [comment]
`first_post_id` can be removed, it is no longer relevant as we recently added `user_id` to the `discussions` migration.

**Comment by Dylan-DPC** [comment]
how is it related to user?

**Comment by AndreasElia** [comment]
`first_post_id` and `last_post_id` should hold user IDs. It might be worth renaming `last_post_id` to `last_post_user_id` or something of sorts?

It was relevant to the user when we never had the `user_id` column inside of `discussions`.

**Comment by byCedric** [comment]
Just to clarify and "close" this issue once and for al. As discussed in the Larachat;

- `first_post_id` and `last_post_id` will be removed, the data will be fetched from the `posts()` relationship using `latest` or `oldest` scopes.
- this circular dependency issue in the factory will be ignored and left untouched.

Will create some PR's for this, in the evening (GMT+02:00).

**Comment by Dylan-DPC** [comment]
sounds good

**Comment by byCedric** [comment]
Guess this can now be closed after a PR merge @Dylan-DPC
