### ISSUE TITLE
MVP Roadmap

### ISSUE THREAD

**Issue by Dylan-DPC** [bitporch/laravel-forum#14]
The roadmap for first release. Let me know if I missed out on anything.

- [x] Controllers

- [x] Models

- [x] Routes

- [x] Migrations

- [x] Policy stubs

- [x] Factories

- [x] The Install Command

- [x] Expose API

- [x] UI

- [ ] Tests

**Comment by deleugpn** [comment]
OAuth would be the Repository problem all over again for authentication, no?

**Comment by Dylan-DPC** [comment]
Closing this since it is no longer useful
