### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by deleugpn** [bitporch/laravel-forum#175]
Following the readme, if you run composer require "bitporch/laravel-forum"` you will get 

```
 [InvalidArgumentException]
  Could not find package bitporch/laravel-forum at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

I'm just opening this issue to keep it registered that we need to address this for first release.

Right now the work-around is to add "bitporch/laravel-forum" as "dev-master" to the composer file and run composer update.

**Comment by Dylan-DPC** [comment]
There isn't much to "address" here. The problem will be solved when we release the package. Also you can do `composer require bitporch/laravel-forum @dev`
