### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by AndreasElia** [bitporch/laravel-forum#193]
In PR #191 I had to comment out a test that was testing the deletion of a group, it was throwing a method not allowed yet the route is correct.

**Comment by deleugpn** [comment]
branch group-tests already refactored all tests for groups in #184

**Comment by Dylan-DPC** [comment]
But the test that is failing has been removed from tests pushed in #184

**Comment by AndreasElia** [comment]
Test was removed.
