### ISSUE TITLE
Name suggestions

### ISSUE THREAD

**Issue by Riari** [bitporch/laravel-forum#196]
Every so often, the idea of a new name comes up. Lots of silly suggestions have been made but here are a few legitimate ones:

- illuminate-forum
- firefly-forum
- laravel-firefly

Feel free to add more, but I think these are the only ones being seriously considered atm.

Or we can just leave it as it is, but frankly, I like the idea of giving it a name with more "flare" (no, not Flarum...)

**Comment by AndreasElia** [comment]
laravel-firefly it is.
