### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Dylan-DPC** [bitporch/laravel-forum#22]
Paginating posts, discussions and groups

**Comment by Riari** [comment]
Probably not worth paginating groups. Even the biggest forums wouldn't really benefit from having them split across multiple pages - they're just listed in one go. It's also a pain to implement because of the nesting.

**Comment by Dylan-DPC** [comment]
I agree.

**Comment by AndreasElia** [comment]
Sorted in #85
