### ISSUE TITLE
Use route model binding?

### ISSUE THREAD

**Issue by Riari** [bitporch/laravel-forum#40]
After the discussion in #33, I was thinking route model binding would be one small thing we could do to keep controller methods simple without resorting to repositories. We're making heavy use of resource controllers here, so most actions expect to deal with a model instance anyway.

**Comment by Riari** [comment]
Actually happy to pick this one up once #39 is merged unless anyone else is on it.

**Comment by AndreasElia** [comment]
Feel free to self assign this one 😄

**Comment by AndreasElia** [comment]
Fixed in #88
