### ISSUE TITLE
Category modes

### ISSUE THREAD

**Issue by Riari** [bitporch/laravel-forum#59]
Some modern forums use a flat category/tagging system instead of a traditional hierarchy of categories, so we should probably offer two modes:

- Simple: categories are a flat list. Discussions can be associated with one or more categories (perhaps make that a configurable limit for this mode; Larachat, for instance, has a flat list of 'channels', but you can only select one when creating a discussion.)
- Nested: categories are nestable. Discussions can belong to one category each.

I'm not sure yet about implementation details, but I imagine it would be fairly simple to do with a simple set of config options and using them when defining relationships, storing categories, etc.

Edit: I mean Groups in the context of this package, but you probably knew that.

**Comment by Dylan-DPC** [comment]
Do you want to do this for mvp? I feel it can be done later

**Comment by AndreasElia** [comment]
@Dylan-DPC already asked, yes for MVP.

**Comment by Dylan-DPC** [comment]
relationship, config option and migration done in #111

**Comment by Dylan-DPC** [comment]
What is left from this?

**Comment by AndreasElia** [comment]
Going to close this issue, looking through the initial chat and the code I can't see anything we might be missing.
