### ISSUE TITLE
Discussion and/or post up/down voting

### ISSUE THREAD

**Issue by AndreasElia** [bitporch/laravel-forum#63]
This should be an optional feature enabled in config and disabled by default.

**Comment by tnerbovik** [comment]
Reaction type model: like, hate, follow, vote etc

Than a couple of traits for adding the ability to react to some model, and a trait for making a model available for reactions

Ending up with some stuff like $user->reactOn($post, 'like') ...or making an alias function for easier use $user->toggleLike($post)

**Comment by AndreasElia** [comment]
Keeping the package as barebones are neccessary, this would either be a seperate suggested package or implemented by the end user. Please check #86 for the discussion.
