### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by tomirons** [bitporch/laravel-forum#81]
What if a user wants to get updates on when someone reply's to a discussion? They should be able to receive and email with a link back to the discussion.

**Note:** [Tuxedo](https://github.com/tomirons/tuxedo) is a great package for this!!

**Comment by AndreasElia** [comment]
Would love to add a "subscribe/unsubscribe" button to discussions too for this specific feature.

**Comment by Riari** [comment]
I like this idea, but it's one of those things that isn't really forum-specific. Content subscriptions are more generic and can (or maybe even should) be implemented at the application level, so if we do include this, I'd push for it to be easily disabled/removed.

**Comment by Dylan-DPC** [comment]
This is post-MVP... good idea though. ;)

**Comment by AndreasElia** [comment]
Keeping the package as barebones are neccessary, this would either be a seperate suggested package or implemented by the end user. Please check #86 for the discussion.
