### ISSUE TITLE
Expose REST API

### ISSUE THREAD

**Issue by Riari** [bitporch/laravel-forum#9]
I know I DMed about this already, but I think this would be a major plus: expose RESTful routes that can be used to implement a custom frontend (thinking SPAs mostly), along with Passport compatibility/integration (e.g. config options to specify auth middleware and a way of retrieving the user object after authentication).

For the most part, it would just cover all of the usual CRUD/BREAD operations but should also provide a few special endpoints to fulfil actions like marking groups/discussions as 'viewed', or retrieving usage stats.

**Comment by deleugpn** [comment]
This should not be on MVP, but should be the 1st thing after 1.0, imo.

**Comment by AndreasElia** [comment]
@deleugpn the package should be able to cover a lot of use cases including being available for use in SPAs from launch. REST API is a not very time consuming addition and can easily be done for 1.0.

**Comment by Dylan-DPC** [comment]
We already have most of the routes. Only authentication is left

**Comment by Riari** [comment]
API routes and controllers should be separate from the others, but they won't take much to write. Let's focus on getting the web ones done and as slim as possible first.

Also, we won't need auth routes as users should authenticate via the application itself. At most, I think we just need to give the package user control over middleware assignment and provide some sensible defaults.

**Comment by AndreasElia** [comment]
Resolved in PR #89
