### ISSUE TITLE
Web + API structure?

### ISSUE THREAD

**Issue by Dylan-DPC** [bitporch/laravel-forum#90]
If #89 is merged, it means that when user runs the `forum:install` command, he will receive both Web & API routes.. i'm not sure if this should be expected behaviour or not since a user might not want both web & api routes. Thoughts?

**Comment by NowNewStart** [comment]
Maybe add a second command to install api routes? Like `forum:api:install` or something like that

**Comment by AndreasElia** [comment]
We can add an optional tag such as `--with-api`.
